name: qml_env
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cpuonly=2.0=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=h42c8aad_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.1=h13d4d48_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=24.1=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=3.10.0=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=1.10.1=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=py38h06a4308_0
  - qt-main=5.15.2=hb6262e9_12
  - readline=8.3=hc2a1206_0
  - requests=2.32.3=py38h06a4308_0
  - scikit-learn=0.24.1=py38ha9443f7_0
  - setuptools=75.1.0=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.2=hb25bd0a_1
  - tesseract=5.2.0=hb0d2e87_3
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.0.1=py38h06a4308_0
  - tornado=6.4.1=py38h5eee18b_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.2.3=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - appdirs==1.4.4
      - autograd==1.7.0
      - autoray==0.6.12
      - cachetools==5.5.2
      - networkx==3.1
      - ninja==1.13.0
      - numpy==1.24.4
      - pennylane==0.25.1
      - pennylane-lightning==0.28.0
      - retworkx==0.15.1
      - rustworkx==0.15.1
      - scipy==1.10.1
      - semantic-version==2.10.0
      - toml==0.10.2
prefix: /home/yangxin202522080302/miniconda3/envs/qml_env
